module.exports = {
    RoleController: require("./role.controller"),
    PlanController : require("./plan.controller"),
    OrderController: require("./order.controller"),
    ColorController : require("./color.controller"),
    ServiceController : require("./service.controller"),
    CustomerController : require("./customer.controller"),
    EmployeeController : require("./employee.controller"),
    WaschPiceController : require("./waschPice.controller"),
    StatusOrderController : require("./statusOrder.controller"),
    NameServiceController : require("./nameService.controller"),
    OrderHistoryController : require("./orderHistory.controller"),
    CategoryPiceController : require("./categoryPice.controller"),
    IncludedServiceController : require("./includedService.controller"),
}