module.exports={
    PlanModel:require("./plan.model"),
    OrderModel:require("./order.model"),
    ColorModel:require("./color.model"),
    ServiceModel:require("./service.model"),
    CustomerModel:require("./customer.model"),
    EmployeeModel:require("./employee.model"),
    WashPiceModel:require("./washPiece.model"),
    NameServiceModel:require("./nameService.model"),
    StatusOrderModel:require("./statusOrder.model"),
    CategoryPiceModel:require("./categoryPice.model"),
    OrderHistoryModel:require("./orderHistory.model"),
    IncludeServiceModel:require("./includedServices.model"),
}